Add cluster template to tenant
projectsyn/lieutenant-operator pull request #110
Opened 2020-09-25 11:36 UTC by srueg

A tenant can specify a cluster template which will be used for newly
created clusters and allows templating.

## Checklist

- [x] Keep pull requests small so they can be easily reviewed.
- [x] Update the documentation.
- [x] Update the ./CHANGELOG.md.
- [x] Link this PR to related issues.

Closes #48 and #109 
Supersedes #108

2020-09-25 12:44 UTC, corvus-ch approved these changes

2020-09-30 14:42 UTC, srueg commented
I tested this on the Synfra cluster and it all seems to work so far.
It's deployed in the `lieutenant-dev` namespace, if you want to give it a go.

2020-09-30 14:47 UTC, srueg commented
And here are the changes for the API to allow empty GitRepoURL on clusters: https://github.com/projectsyn/lieutenant-api/pull/86

2020-10-01 07:43 UTC, corvus-ch requested changes
This needs end user documentation explaining how the templating works and how it can be used.

Further we need a follow up to have templating errors being reflected as conditions and events on the effected objects.

2020-10-01 08:04 UTC, srueg commented
Follow up for improved error handling: #112

2020-10-01 14:41 UTC, srueg commented
Ok, I wrote an explanation on how to use the templating.

Also I fixed two bugs if the tenant or cluster GitRepoTemplate is empty. Now, no GitRepo object is created (as it was described in the docs).

2020-10-02 06:41 UTC, corvus-ch requested changes
Examples are good to have but they tend to be insufficient. Too much that is left to interpretation and or might be missed. Please explain the rules of how access fields in more detail.

2020-10-02 06:41 UTC, corvus-ch commented on docs/modules/ROOT/pages/explanations/templating.adoc
> +      creation: '{{ .CreationTimestamp }}'
Please explicitly state that `.metadata.…` fields are embedded and are accessible directly.

2020-10-02 06:41 UTC, corvus-ch commented on docs/modules/ROOT/pages/explanations/templating.adoc
> +      path: cluster-catalogs/{{ index .Spec.Facts "cloud"}}
Please explicitly state that the `index` function must be used when accessing dicts.

2020-10-02 08:07 UTC, corvus-ch requested changes

2020-10-02 08:07 UTC, corvus-ch commented on docs/modules/ROOT/pages/explanations/templating.adoc
> +[INFO]
```suggestion
[NOTE]
```

INFO is not a known admonition. See https://asciidoctor.org/docs/user-manual/#admonition.

2020-10-02 08:07 UTC, corvus-ch commented on docs/modules/ROOT/pages/explanations/templating.adoc
> +[INFO]
```suggestion
[NOTE]
```

2020-10-02 08:21 UTC, simu approved these changes

2020-10-02 08:23 UTC, corvus-ch approved these changes

2020-10-02 08:36 UTC, tobru approved these changes

2020-10-02 11:54 UTC, merged